version: "3.8"
services:
  web:
    container_name: nginx_container
    image: nginx_image
    build: requirements/nginx/
    ports:
    - "443:443"

  mariadb:
    container_name: mariadb_container
    image: mariadb_image
    build: requirements/mariadb/
    ports:
    - "3306:3306"

  wordpress:
    container_name: wordpress_container
    image: wordpress_image
    build: requirements/wordpress
    depends_on:
      - web
      - mariadb
    ports:
    - "9000:9000"