version: "3.8"

services:

  #############
  ## MariaDB ##
  #############

  mariadb:
    container_name: mariadb_container
    image: mariadb
    restart: unless-stopped
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - maria-volume:/var/lib/mysql/
    env_file: .env
    networks:
      - my-network

  ###############
  ## WordPress ##
  ###############

  wordpress:
    container_name: wordpress_container
    image: wordpress
    restart: unless-stopped
    build: requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wordpress-volume:/var/www/html
    env_file: .env
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ###########
  ## Nginx ##
  ###########

  nginx:
    container_name: nginx_container
    image: nginx
    restart: unless-stopped
    build: requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    env_file: .env
    networks:
      - my-network

#############
## Network ##
#############
networks:
  my-network:
    driver: bridge

#############
## Volumes ##
#############
volumes:
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/ndormoy/data/wordpress
      o: bind

  maria-volume:
    name: maria-volume
    driver: local
    driver_opts:
      type: none
      device: /home/ndormoy/data/mariadb
      o: bind